/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCaptureRouteImport } from './routes/app/capture'
import { Route as AppCoachRouteImport } from './routes/app/coach'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppLoyaltyRouteImport } from './routes/app/loyalty'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppShopRouteImport } from './routes/app/shop'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsActivityRouteImport } from './routes/ops.activity'
import { Route as OpsSupportRouteImport } from './routes/ops.support'
import { Route as OpsTeamRouteImport } from './routes/ops.team'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppInboxIndexRouteImport } from './routes/app/inbox.index'
import { Route as AppInboxIdRouteImport } from './routes/app/inbox.$id'
import { Route as AppPeopleIndexRouteImport } from './routes/app/people.index'
import { Route as AppPeopleIdRouteImport } from './routes/app/people.$id'
import { Route as OpsShopsIndexRouteImport } from './routes/ops.shops.index'
import { Route as OpsShopsIdRouteImport } from './routes/ops.shops.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActivityRoute = OpsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSupportRoute = OpsSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => OpsRoute,
} as any)
const OpsTeamRoute = OpsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OpsRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRoute,
} as any)
const OpsShopsIndexRoute = OpsShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsShopsIdRoute = OpsShopsIdRouteImport.update({
  id: '/shops/$id',
  path: '/shops/$id',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/playbook': typeof PlaybookRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/coach': typeof AppCoachRoute
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/shop': typeof AppShopRoute
  '/app/support': typeof AppSupportRoute
  '/ops/activity': typeof OpsActivityRoute
  '/ops/support': typeof OpsSupportRoute
  '/ops/team': typeof OpsTeamRoute
  '/s/$code': typeof SCodeRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/ops/shops/$id': typeof OpsShopsIdRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/ops/shops/': typeof OpsShopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/coach': typeof AppCoachRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/shop': typeof AppShopRoute
  '/app/support': typeof AppSupportRoute
  '/ops/activity': typeof OpsActivityRoute
  '/ops/support': typeof OpsSupportRoute
  '/ops/team': typeof OpsTeamRoute
  '/s/$code': typeof SCodeRoute
  '/app': typeof AppIndexRoute
  '/ops': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/ops/shops/$id': typeof OpsShopsIdRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/people': typeof AppPeopleIndexRoute
  '/ops/shops': typeof OpsShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/playbook': typeof PlaybookRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/coach': typeof AppCoachRoute
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/shop': typeof AppShopRoute
  '/app/support': typeof AppSupportRoute
  '/ops/activity': typeof OpsActivityRoute
  '/ops/support': typeof OpsSupportRoute
  '/ops/team': typeof OpsTeamRoute
  '/s/$code': typeof SCodeRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/ops/shops/$id': typeof OpsShopsIdRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/ops/shops/': typeof OpsShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/ops'
    | '/playbook'
    | '/reset-password'
    | '/app/capture'
    | '/app/coach'
    | '/app/inbox'
    | '/app/loyalty'
    | '/app/people'
    | '/app/shop'
    | '/app/support'
    | '/ops/activity'
    | '/ops/support'
    | '/ops/team'
    | '/s/$code'
    | '/app/'
    | '/ops/'
    | '/api/auth/$'
    | '/app/inbox/$id'
    | '/app/people/$id'
    | '/ops/shops/$id'
    | '/app/inbox/'
    | '/app/people/'
    | '/ops/shops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/playbook'
    | '/reset-password'
    | '/app/capture'
    | '/app/coach'
    | '/app/loyalty'
    | '/app/shop'
    | '/app/support'
    | '/ops/activity'
    | '/ops/support'
    | '/ops/team'
    | '/s/$code'
    | '/app'
    | '/ops'
    | '/api/auth/$'
    | '/app/inbox/$id'
    | '/app/people/$id'
    | '/ops/shops/$id'
    | '/app/inbox'
    | '/app/people'
    | '/ops/shops'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/ops'
    | '/playbook'
    | '/reset-password'
    | '/app/capture'
    | '/app/coach'
    | '/app/inbox'
    | '/app/loyalty'
    | '/app/people'
    | '/app/shop'
    | '/app/support'
    | '/ops/activity'
    | '/ops/support'
    | '/ops/team'
    | '/s/$code'
    | '/app/'
    | '/ops/'
    | '/api/auth/$'
    | '/app/inbox/$id'
    | '/app/people/$id'
    | '/ops/shops/$id'
    | '/app/inbox/'
    | '/app/people/'
    | '/ops/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PlaybookRoute: typeof PlaybookRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SCodeRoute: typeof SCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capture': {
      id: '/app/capture'
      path: '/capture'
      fullPath: '/app/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loyalty': {
      id: '/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activity': {
      id: '/ops/activity'
      path: '/activity'
      fullPath: '/ops/activity'
      preLoaderRoute: typeof OpsActivityRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/support': {
      id: '/ops/support'
      path: '/support'
      fullPath: '/ops/support'
      preLoaderRoute: typeof OpsSupportRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/team': {
      id: '/ops/team'
      path: '/team'
      fullPath: '/ops/team'
      preLoaderRoute: typeof OpsTeamRouteImport
      parentRoute: typeof OpsRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inbox/': {
      id: '/app/inbox/'
      path: '/'
      fullPath: '/app/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/app/inbox/$id': {
      id: '/app/inbox/$id'
      path: '/$id'
      fullPath: '/app/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/app/people/': {
      id: '/app/people/'
      path: '/'
      fullPath: '/app/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/app/people/$id': {
      id: '/app/people/$id'
      path: '/$id'
      fullPath: '/app/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/ops/shops/': {
      id: '/ops/shops/'
      path: '/shops'
      fullPath: '/ops/shops/'
      preLoaderRoute: typeof OpsShopsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/shops/$id': {
      id: '/ops/shops/$id'
      path: '/shops/$id'
      fullPath: '/ops/shops/$id'
      preLoaderRoute: typeof OpsShopsIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppPeopleRouteChildren {
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppRouteChildren {
  AppCaptureRoute: typeof AppCaptureRoute
  AppCoachRoute: typeof AppCoachRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppShopRoute: typeof AppShopRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaptureRoute: AppCaptureRoute,
  AppCoachRoute: AppCoachRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppShopRoute: AppShopRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OpsRouteChildren {
  OpsActivityRoute: typeof OpsActivityRoute
  OpsSupportRoute: typeof OpsSupportRoute
  OpsTeamRoute: typeof OpsTeamRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsShopsIdRoute: typeof OpsShopsIdRoute
  OpsShopsIndexRoute: typeof OpsShopsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsActivityRoute: OpsActivityRoute,
  OpsSupportRoute: OpsSupportRoute,
  OpsTeamRoute: OpsTeamRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsShopsIdRoute: OpsShopsIdRoute,
  OpsShopsIndexRoute: OpsShopsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PlaybookRoute: PlaybookRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SCodeRoute: SCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
